#!/bin/bash


# tools all the packages I will need
sudo pacman -S --noconfirm tmux feh fzf stow brave-browser obsidian kubectl \
    ttf-ubuntu-mono-nerd go rofi --noconfirm


FILE=/bin/zsh
if test ! -f "$FILE"; then
	# installing oh-my-zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

fi
